name: Storm CMS Core
description: Base recipe to install the required modules and configurations.
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_admin_theme
  - core/recipes/core_recommended_front_end_theme
  - core/recipes/core_recommended_performance
install:
  - automated_cron
  - block
  - block_content
  - config
  - contextual
  - dblog
  - field_ui
  - help
  - menu_link_content
  - menu_ui
  - navigation
  - node
  - page_cache
  - path
  - views
  - views_ui
  - advagg
  - antibot
  - easy_breadcrumb
  - environment_indicator
  - google_tag
  - honeypot
  - link_attributes
  - link_attributes_menu_link_content
  - login_destination
  - pathauto
  - r4032login
  - redirect
  - redirect_404
  - responsive_preview
  - robotstxt
  - seckit
  - simple_sitemap
  - sitemap
  - ultimate_cron
config:
  import:
    automated_cron:
      - automated_cron.settings
    block_content:
      - views.view.block_content.yml
    dblog:
      - views.view.watchdog
    system:
      - system.cron
    pathauto: '*'
    responsive_preview: '*'
    redirect:
      - redirect.settings
      - system.action.redirect_delete_action
      - views.view.redirect
    seckit: "*"
    simple_sitemap: '*'
    sitemap:
      - sitemap.settings
    ultimate_cron: '*'
  actions:
    block.block.olivero_branding:
      simple_config_update:
        status: false
    block.block.olivero_tools:
      simple_config_update:
        status: false
    block.block.olivero_admin:
      simple_config_update:
        status: false
    block.block.olivero_local_tasks:
      simple_config_update:
        status: false
    block.block.olivero_local_actions:
      simple_config_update:
        status: false
    block.block.claro_tools:
      simple_config_update:
        status: false
    block.block.claro_branding:
      simple_config_update:
        status: false
    block.block.claro_admin:
      simple_config_update:
        status: false
    block.block.claro_local_tasks:
      simple_config_update:
        status: false
    block.block.olivero_page_title:
      simple_config_update:
        region: content_above
        weight: -10
    block.block.claro_page_title:
      simple_config_update:
        region: header
        weight: -10
    views.settings:
      simple_config_update:
        ui.show:
          default_display: true
          advanced_column: true
          preview_information: true
          sql_query:
            enabled: true
            where: above
    system.date:
      simple_config_update:
        country.default: US
        timezone.default: America/New_York
        timezone.user.configurable: false
    system.performance:
      simple_config_update:
        cache.page.max_age: 21600
        css.preprocess: true
        js.preprocess: true
    easy_breadcrumb.settings:
      simple_config_update:
        add_structured_data_json_ld: true
        hide_single_home_item: true
    honeypot.settings:
      simple_config_update:
        form_settings:
          user_pass: true
          user_register_form: true
    seckit.settings:
      simple_config_update:
        seckit_xss.csp:
          checkbox: true
          vendor-prefix:
            x: true
    user.role.authenticated:
      grantPermissions:
        - 'bypass honeypot protection'
        - 'skip antibot'

