name: Storm CMS Core
description: Base recipe to install the required modules and configurations.
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_admin_theme
  - core/recipes/core_recommended_front_end_theme
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
install:
  - contextual
  - config
  - field_ui
  - help
  - menu_link_content
  - menu_ui
  - navigation
  - path
  - phpass
  - settings_tray
  - views_ui
  - antibot
  - backup_migrate
  - easy_breadcrumb
  - environment_indicator
  - eca
  - honeypot
  - link_attributes
  - link_attributes_menu_link_content
  - login_destination
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - metatag_views
  - minifyhtml
  - pathauto
  - r4032login
  - redirect
  - responsive_preview
  - robotstxt
  - select2
  - simple_sitemap
  - ultimate_cron
  - advagg_bundler
  - advagg_ext_minify
  - advagg_css_minify
  - advagg_js_minify
  - advagg_mod
  - advagg
config:
  import:
    dblog: '*'
    metatag:
      - metatag.metatag_defaults.403
      - metatag.metatag_defaults.404
      - metatag.metatag_defaults.front
      - metatag.metatag_defaults.global
      - metatag.settings
    pathauto: '*'
    responsive_preview: '*'
    redirect:
      - redirect.settings
      - system.action.redirect_delete_action
      - views.view.redirect
    simple_sitemap: '*'
    ultimate_cron: '*'
  actions:
    block.block.olivero_branding:
      simple_config_update:
        status: false
    block.block.olivero_tools:
      simple_config_update:
        status: false
    block.block.olivero_admin:
      simple_config_update:
        status: false
    block.block.olivero_local_tasks:
      simple_config_update:
        status: false
    block.block.olivero_local_actions:
      simple_config_update:
        status: false
    block.block.claro_tools:
      simple_config_update:
        status: false
    block.block.claro_branding:
      simple_config_update:
        status: false
    block.block.claro_admin:
      simple_config_update:
        status: false
    block.block.claro_local_tasks:
      simple_config_update:
        status: false
    block.block.olivero_page_title:
      simple_config_update:
        region: content_above
        weight: -10
    block.block.claro_page_title:
      simple_config_update:
        region: header
        weight: -10
    views.settings:
      simple_config_update:
        ui.show:
          default_display: true
          advanced_column: true
          sql_query:
            enabled: true
    system.date:
      simple_config_update:
        country.default: US
        timezone.default: America/New_York
        timezone.user.configurable: false
    system.performance:
      simple_config_update:
        cache.page.max_age: 21600
        css.preprocess: true
        js.preprocess: true
    easy_breadcrumb.settings:
      simple_config_update:
        add_structured_data_json_ld: true
        hide_single_home_item: true
    honeypot.settings:
      simple_config_update:
        form_settings:
          user_pass: true
          user_register_form: true
    minifyhtml.config:
      simple_config_update:
        strip_comments: true
        minify: true
        exclude_pages: '/admin*'
    user.role.authenticated:
      grantPermissions:
        - 'bypass honeypot protection'
        - 'skip antibot'
    advagg_bundler.settings:
      simple_config_update:
        css:
          logic: 1
          max: 4
        js:
          logic: 1
          max: 4
    advagg_js_minify.settings:
      simple_config_update:
        minifier: 4
    advagg.settings:
      simple_config_update:
        dns_prefetch: true
    advagg_mod.settings:
      simple_config_update:
        css_adjust_sort_browsers: true
        css_adjust_sort_external: true
        css_preprocess: true
        js_adjust_sort_external: true
        js_adjust_sort_browsers: true
        js_preprocess: true

