name: Storm CMS Core
description: Base recipe to install the required modules and conifgurations.
recipes:
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/basic_block_type
  - core/recipes/image_media_type
  - core/recipes/local_video_media_type
  - core/recipes/remote_video_media_type
  - core/recipes/standard_responsive_images
  - core/recipes/editorial_workflow
  - core/recipes/core_recommended_admin_theme
  - core/recipes/core_recommended_front_end_theme
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
install:
  - contextual
  - config
  - field_ui
  - help
  - menu_link_content
  - menu_ui
  - navigation
  - path
  - phpass
  - settings_tray
  - views_ui
  - backup_migrate
  - easy_breadcrumb
  - environment_indicator
  - eca
  - link_attributes
  - link_attributes_menu_link_content
  - metatag
  - minifyhtml
  - pathauto
  - redirect
  - responsive_preview
  - robotstxt
  - simple_sitemap
  - ultimate_cron
config:
  import:
    dblog: '*'
    pathauto: '*'
    responsive_preview: '*'
    redirect:
      - redirect.settings
      - system.action.redirect_delete_action
      - views.view.redirect
    simple_sitemap: '*'
    ultimate_cron: '*'
  actions:
    block.block.olivero_branding:
      simple_config_update:
        status: false
    block.block.olivero_tools:
      simple_config_update:
        status: false
    block.block.olivero_admin:
      simple_config_update:
        status: false
    block.block.olivero_local_tasks:
      simple_config_update:
        status: false
    block.block.olivero_local_actions:
      simple_config_update:
        status: false
    block.block.claro_tools:
      simple_config_update:
        status: false
    block.block.claro_branding:
      simple_config_update:
        status: false
    block.block.claro_admin:
      simple_config_update:
        status: false
    block.block.claro_local_tasks:
      simple_config_update:
        status: false
    block.block.olivero_page_title:
      simple_config_update:
        region: content_above
        weight: -10
    block.block.claro_page_title:
      simple_config_update:
        region: header
        weight: -10
    views.settings:
      simple_config_update:
        ui.show:
          default_display: true
          advanced_column: true
          sql_query.enabled: true
    system.date:
      simple_config_update:
        country.default: US
        timezone.default: America/New_York
        timezone.user.configurable: false
    system.performance:
      simple_config_update:
        cache.page.max_age: 21600
        css.preprocess: true
        js.preprocess: true
    minifyhtml.config:
      simple_config_update:
        strip_comments: true
        minify: true
        exclude_pages: '/admin*'
    easy_breadcrumb.settings:
      simple_config_update:
        add_structured_data_json_ld: true
        hide_single_home_item: true

